### ISSUE TITLE
explore Mux integration

### ISSUE THREAD

**Issue by jessica-christie** [SYNQfm/doppelganger#2]
We could pass a parameter to Knowi, like web_id or project_id. Knowi then gets the data it needs from our db and then pulls the analytics from Mux. Data will be displayed in the dashboard of the project.

Ex. Get all video ids from db for a project and get usage from mux.

**Comment by jessica-christie** [comment]
@halvardos and @batmany13 this is here if you want to add to anything.

**Comment by batmany13** [comment]
@jessica-christie I added this to the "In-Progress" pipeline and assigned it to you.  I also added an estimate.  I think you'll have to install Zenhub in order to see some of this  stuff.

**Comment by jessica-christie** [comment]
We're not continuing with Knowi since it is cost prohibitive. Closing this issue @batmany13 .
